### ISSUE TITLE
Problem downloading flowCore within cytofCore

### ISSUE THREAD

**Issue by dmrodriguez** [nolanlab/cytofCore#2]
> install_github("nolanlab/cytofCore")
Downloading github repo nolanlab/cytofCore@master
Installing cytofCore
Skipping 1 packages not available: flowCore
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/jq/jn6mhdv90w3dgyy8360qzqdc0000gn/T/Rtmp3kuJjm/devtoolsb526298b47d/nolanlab-cytofCore-d15dc57'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

ERROR: dependency ‘flowCore’ is not available for package ‘cytofCore’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/cytofCore’
Error: Command failed (1)

(Please help)

**Comment by rfinck** [comment]
You need to install flowCore, which you can do with the following commands:
`source("http://bioconductor.org/biocLite.R")`
`biocLite("flowCore") `

See http://www.bioconductor.org/packages/release/bioc/html/flowCore.html
