### ISSUE TITLE
Issue with cytofCore function

### ISSUE THREAD

**Issue by horowitzamir** [nolanlab/cytofCore#5]

**Comment by horowitzamir** [comment]
I am having a problem using the cytofCore function. I have gone through step by step from your github page. When i finally type the command:
> cytofCore.updatePanel()

I get the following error message:

Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.1/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /usr/X11/lib/libXft.2.dylib
  Referenced from: /usr/local/lib/libtk8.6.dylib
  Reason: image not found
Error: package or namespace load failed for ‘tcltk’

Can soeone please help me?

Thanks
Amir

**Comment by esimonds** [comment]
Hi Amir,

I think this error indicates that X11 (now called XQuartz) is not installed on your system.  This is a Mac-specific issue. X11 used to be installed by default with OS X, but later version (starting with Yosemite, I believe) dropped it.

Please try installing XQuartz as described here:
https://support.apple.com/en-us/HT201341

...and please report your success or failure.  Thanks!

**Comment by horowitzamir** [comment]
Hi Erin,

Thanks so much for getting back to me. And sorry for the delayed response. I really appreciate your help. This was indeed the problem, and now it is resolved.

Thanks again.
best wishes
Amir
_______________
Amir Horowitz, PhD
Research Scientist / Departments of Structural Biology and Microbiology & Immunology / Parham Laboratory / Stanford University School of Medicine / Fairchild Building / Room D100 / 299 Campus Drive West, Stanford CA 94305-5126 / http://www.stanford.edu/group/parhamlab





On Mar 2, 2016, at 1:06 PM, Erin Simonds <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Amir,

I think this error indicates that X11 (now called XQuartz) is not installed on your system. This is a Mac-specific issue. X11 used to be installed by default with OS X, but later version (starting with Yosemite, I believe) dropped it.

Please try installing XQuartz as described here:
https://support.apple.com/en-us/HT201341

...and please report your success or failure. Thanks!

**Comment by esimonds** [comment]
Awesome, thanks for the report. Closing.
